"""Run the same Google News SEO queries five times and assess result stability.

The script keeps all results in memory and prints DataFrames; it does not write
query-result CSV files.  Each run makes up to 20 x 5 live DataForSEO requests.
"""

import base64
import os
import re
from pathlib import Path

import pandas as pd
import requests


BASE_URL = 'https://api.dataforseo.com/v3'
REQUEST_TIMEOUT = (15, 120)
N_LOCATIONS = 20
# Run the same query five times for each location-country pair.
# The five returned article counts are compared to assess short-term stability.
N_ROUNDS = 5
SEARCH_TERMS = 'conflict OR war OR attack OR armed OR terror OR bomb OR violence OR strike OR protest'
DATE_FILTER = 'tbs=cdr:1,cd_min:01/01/2026,cd_max:05/31/2026'

COUNTRY_ALIASES = {
    # Use the exact Country-level names in dataforseo_google_location_codes.csv.
    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
    'Congo, DR': 'Democratic Republic of the Congo',
    'DR Congo': 'Democratic Republic of the Congo',
    'Democratic Republic of Congo': 'Democratic Republic of the Congo',
    'Republic of Congo': 'Republic of the Congo',
    'Congo, Republic of the': 'Republic of the Congo',
    'United Arab Emirates (UAE)': 'United Arab Emirates',
    'UAE': 'United Arab Emirates',
}
LOCATION_SUFFIXES = re.compile(
    r'\b(town|city|village|district|province|county|region|municipality|'
    r'governorate|canton|prefecture|state|department|refugee camp|'
    r'state border crossing)\b',
    flags=re.IGNORECASE,
)


def load_dotenv(path: Path) -> None:
    """Load simple KEY=VALUE settings without an extra dependency."""
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def clean_location(value):
    if pd.isna(value):
        return None
    value = LOCATION_SUFFIXES.sub('', str(value).strip()).strip()
    value = re.sub(r'[\s,;]+$', '', value).strip()
    return value or None


def clean_country(value):
    if pd.isna(value):
        return None
    value = re.sub(r'\s*\(.*?\)\s*', '', str(value).strip()).strip()
    return COUNTRY_ALIASES.get(value, value) or None


def load_conflict_pairs() -> pd.DataFrame:
    """Use conflictclean when present; otherwise create it from the raw GDELT file."""
    for filename in ('conflictclean.csv', 'conflict_clean.csv'):
        path = Path(filename)
        if path.exists():
            frame = pd.read_csv(path)
            if {'location_clean', 'country_clean'}.issubset(frame.columns):
                pairs = frame[['location_clean', 'country_clean']].copy()
                break
            if {'location', 'country'}.issubset(frame.columns):
                pairs = frame.rename(
                    columns={'location': 'location_clean', 'country': 'country_clean'}
                )[['location_clean', 'country_clean']].copy()
                break
            raise ValueError(f'{filename} must contain location/country or location_clean/country_clean.')
    else:
        raw = pd.read_csv('GEDEvent_v26_0_4.csv')
        pairs = pd.DataFrame({
            'location_clean': raw['where_coordinates'].map(clean_location),
            'country_clean': raw['country'].map(clean_country),
        })

    pairs['location_clean'] = pairs['location_clean'].map(clean_location)
    pairs['country_clean'] = pairs['country_clean'].map(clean_country)
    pairs = pairs.dropna().drop_duplicates().head(N_LOCATIONS).reset_index(drop=True)
    if pairs.empty:
        raise ValueError('No usable location-country combinations were found.')
    return pairs


def get_headers() -> dict:
    load_dotenv(Path(__file__).with_name('.env'))
    login = os.environ.get('DFSEO_LOGIN')
    password = os.environ.get('DFSEO_PASSWORD')
    if not login or not password:
        raise RuntimeError('Set DFSEO_LOGIN and DFSEO_PASSWORD in .env or environment variables.')
    credentials = base64.b64encode(f'{login}:{password}'.encode()).decode()
    return {'Authorization': f'Basic {credentials}', 'Content-Type': 'application/json'}


def get_country_location_codes() -> dict[str, int]:
    """Read the vendor-supplied location table generated by location_code.py.

    This contains separate codes for Democratic Republic of the Congo (CD,
    2180) and Republic of the Congo (CG, 2178).
    """
    locations_path = Path('dataforseo_google_location_codes.csv')
    if not locations_path.exists():
        raise FileNotFoundError(
            'Run location_code.py first to create dataforseo_google_location_codes.csv.'
        )
    location_table = pd.read_csv(locations_path, usecols=['location_code', 'location_name', 'location_type'])
    countries = location_table[location_table['location_type'].eq('Country')]
    return {
        str(row.location_name).strip().casefold(): int(row.location_code)
        for row in countries.itertuples(index=False)
    }


def run_query(headers: dict, country: str, location: str, location_code: int, round_number: int):
    keyword = f'({SEARCH_TERMS}) AND "{country}" AND "{location}"'
    payload = [{
        'language_code': 'en',
        'keyword': keyword,
        'depth': 1,
        'search_param': DATE_FILTER,
        'location_code': location_code,
        'tag': f'stability_r{round_number}_{country}_{location}',
    }]

    try:
        response = requests.post(
            f'{BASE_URL}/serp/google/news/live/advanced',
            headers=headers,
            json=payload,
            timeout=REQUEST_TIMEOUT,
        )
        response.raise_for_status()
        api_response = response.json()
    except requests.exceptions.Timeout:
        return pd.NA, 'request_timeout'
    except requests.RequestException as exc:
        return pd.NA, f'request_error: {exc.__class__.__name__}'
    except ValueError:
        return pd.NA, 'invalid_json'

    if api_response.get('status_code') != 20000:
        return pd.NA, f"api_error: {api_response.get('status_code')}"

    task = (api_response.get('tasks') or [{}])[0]
    task_status = task.get('status_code')
    # 40102 is a completed query with zero search results.
    if task_status not in {20000, 40102}:
        return pd.NA, f"task_error: {task_status}"

    for result in task.get('result') or []:
        if result.get('se_results_count') is not None:
            return result['se_results_count'], 'ok' if task_status == 20000 else 'no_results'
    return pd.NA, 'missing_result_count'


def classify_stability(row: pd.Series) -> str:
    # Use only the five article-count columns for the stability decision.
    values = row[[f'query_{number}' for number in range(1, N_ROUNDS + 1)]].dropna()

    # A failed request or an unsupported location leaves a missing value.
    # Such rows cannot be compared fairly across all five rounds.
    if len(values) < N_ROUNDS:
        return 'incomplete'

    # Identical counts mean that the result volume did not change at all.
    if values.nunique() == 1:
        return 'perfectly stable' if values.iloc[0] != 0 else 'consistently zero'

    # The coefficient of variation (sample standard deviation / mean) measures
    # variation relative to the typical result count.  A smaller value means
    # that repeated queries returned more similar article counts.
    mean = values.mean()
    coefficient_of_variation = values.std(ddof=1) / mean if mean else float('inf')

    # Thresholds used for the final stability label:
    # CV < 0.05: highly stable; CV < 0.20: moderately stable; otherwise unstable.
    if coefficient_of_variation < 0.05:
        return 'highly stable'
    if coefficient_of_variation < 0.20:
        return 'moderately stable'
    return 'unstable'


def run_stability_test() -> pd.DataFrame:
    pairs = load_conflict_pairs()
    headers = get_headers()
    country_codes = get_country_location_codes()
    rows = []

    for pair_number, pair in pairs.iterrows():
        country = pair['country_clean']
        location = pair['location_clean']
        location_code = country_codes.get(country.casefold())
        row = {
            'pair_number': pair_number + 1,
            'country': country,
            'location': location,
            'location_code': location_code,
            'keyword_query': f'({SEARCH_TERMS}) AND "{country}" AND "{location}"',
        }

        for round_number in range(1, N_ROUNDS + 1):
            if location_code is None:
                count, status = pd.NA, 'unsupported_location'
            else:
                print(f'Round {round_number}/{N_ROUNDS}: {country} | {location}')
                count, status = run_query(headers, country, location, location_code, round_number)
            row[f'query_{round_number}'] = count
            row[f'status_{round_number}'] = status
        rows.append(row)

    results = pd.DataFrame(rows)
    query_columns = [f'query_{number}' for number in range(1, N_ROUNDS + 1)]
    numeric_results = results[query_columns].apply(pd.to_numeric, errors='coerce')

    # Descriptive statistics across the five identical queries.  ddof=1 uses
    # the sample standard deviation, appropriate for five repeated observations.
    results['mean_article_count'] = numeric_results.mean(axis=1)
    results['std_article_count'] = numeric_results.std(axis=1, ddof=1)
    results['min_article_count'] = numeric_results.min(axis=1)
    results['max_article_count'] = numeric_results.max(axis=1)
    results['range_article_count'] = results['max_article_count'] - results['min_article_count']

    # The coefficient of variation is undefined when the mean is zero.  Those
    # rows are classified separately as "consistently zero" when all rounds are zero.
    results['coefficient_of_variation'] = (
        results['std_article_count'] / results['mean_article_count']
    ).where(results['mean_article_count'].ne(0))
    results['stability'] = results.apply(classify_stability, axis=1)
    return results


def print_stability_analysis(results: pd.DataFrame) -> None:
    print('\nFive-query comparison DataFrame:')
    print(results.to_string(index=False))
    print('\nStability analysis:')
    print(results['stability'].value_counts(dropna=False).rename_axis('stability').to_frame('locations'))
    complete = results[results['stability'] != 'incomplete']
    if not complete.empty:
        print(f"Mean within-location standard deviation: {complete['std_article_count'].mean():.2f}")
        print(f"Perfectly stable or consistently-zero locations: {(complete['stability'].isin(['perfectly stable', 'consistently zero'])).sum()} / {len(complete)}")


if __name__ == '__main__':
    stability_results = run_stability_test()
    print_stability_analysis(stability_results)
